version: '3'
services:
  db:
    image: mysql:5.7
    container_name: Mission20_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iii
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d/ 
