version: '3'
services:
  jupyter-tutorial:
    image: jupyter/base-notebook
    container_name: Mission6 
    ports:
      - "7777:8888"
    volumes:
      - ./work:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iii
#  admin:
#    image: adminer
#    ports:
#      - 8080:8080
    
